### ISSUE TITLE
few issues if this thing is alive

### ISSUE THREAD

**Issue by JayFlowGT** [Xwilarg/NHentaiAnalytics#1] opened 2020-08-18 23:26 UTC
![image](https://user-images.githubusercontent.com/40595555/90574554-854f7d80-e1b9-11ea-8fad-76e9c3036ac3.png)

issues related to the picture:

[1] on detection of new/added doujins it reloads the entire list of tags.

[2] the window for this process needs to be open for its entirety, but clicking anywhere on the browser closes it.

[3] the suggestion option is just straight up broken for me and stays in loading seemingly forever.

otherwise just wanted to say that even though it is heavily underused this is a pretty neat extension.
especially because it kind of works like a visualized catalog that nhentai themselves dont offer.

**Comment by Xwilarg** [comment] 2020-08-18 23:35
Hi,

Thanks for your message, I stopped developing this extension when NHentai released their "Popular" feature but I'm glad to hear that you like it!

For your first issue, I was doing that because I didn't really have a mean to know what doujin was added / removed so I have to reload everything to get the new tags (I can't store what doujin you currently have because Chrome storage isn't big enough)

For your others issues I'll try to look into them either this week or the next one and will send you a message after updating the extension (the 3rd one is probably related to the fact that I didn't update the extension after the API changes)
   Le mercredi 19 août 2020 à 01:27:08 UTC+2, JayFlowGT <notifications@github.com> a écrit :  
 
 




issues related to the picture:

[1] on detection of new/added doujins it reloads the entire list of tags.

[2] the window for this process needs to be open for its entirety, but clicking anywhere on the browser closes it.

[3] the suggestion option is just straight up broken for me and stays in loading seemingly forever.

otherwise just wanted to say that even though it is heavily underused this is a pretty neat extension.
especially because it kind of works like a visualized catalog that nhentai themselves dont offer.

**Comment by JayFlowGT** [comment] 2020-08-18 23:45
great to see how active you are.

my uneducated idea would have been to just store the user aswell as the ids of doujins related to them, but if thats already above storage capacity i guess there is nothing to be done.

ill be looking forward to the update anyway. although i might just be one of few ^^'

**Comment by JayFlowGT** [comment] 2020-08-19 00:44
one thing to add i just found out.
if its updating after you open the window, but open the settings page, it keeps updating regardless of wether the window is open or not as long as the settings page stay opened.

**Comment by Xwilarg** [comment] 2020-08-19 01:06
Good to know, thanks :)
   Le mercredi 19 août 2020 à 02:45:13 UTC+2, JayFlowGT <notifications@github.com> a écrit :  
 
 


one thing to add i just found out.
if its updating after you open the window, but open the settings page, it keeps updating regardless of wether the window is open or not as long as the settings page stay opened.

**Comment by Xwilarg** [comment] 2020-09-11 16:32
Hey,
So I'm just letting you a small message to let you know that I didn't give up on this.
I've been very busy on some others projects so it might still take me some weeks before being able to be back on this one.

**Comment by JayFlowGT** [comment] 2020-12-08 21:00
So its been 3 months.
Any idea if you are going to pick this up again or this project done for?

**Comment by Xwilarg** [comment] 2020-12-08 21:32
Yeah sorry about that, I worked a bit on it and after that I kept telling procrastinating by working on others projects...

I'll go work on it this thursday and tell you before friday how things are going (CET time).

**Comment by Xwilarg** [comment] 2020-12-10 17:08
So that took me a long time but I finally fixed the bugs!
I sent it on the Chrome store (will need to wait a bit for them to review it), but it's also available on the Release page: https://github.com/Xwilarg/NHentaiAnalytics/releases/tag/v1.2.1

Please tell me what you think of it and if you find anything I forgot (or if you have some others suggestions)
Don't worry, next updates will take less time now that I went back to understand my code a bit :p

**Comment by JayFlowGT** [comment] 2020-12-18 00:40
Updating seems to be working fine and the suggestion has been fixed. The only thing missing would be a way to not have to reload all tags, but instead just update the list with favorites that were added/deleted since the last time. Which wouldn't be that big of a problem, but the tag loading takes a long time, which is probably API related anyway, so that really would be the last thing I see as an annoyance besides the blinding white screen on the settings page. Dark mode 👀 If you are really bored or feeling like it.

Otherwise good update 👍

**Comment by JayFlowGT** [comment] 2020-12-18 01:59
Or so I thought. The suggestion now shows me a certain doujin, but when clicking it opens a different one. This 
didn't happen the first time around. I think it started after I reloaded tags a second time.

**Comment by Xwilarg** [comment] 2020-12-18 09:06
I indeed noticed the same issue for the URL leading to the wrong page, I'll investigate why this is happening.
For the dark theme that shouldn't be too hard too so I'll see if I can do something nice.

For the last point, "not reloading everything", this one would take more time but on the long term I'll need to do it too.

For now, I'll do the firsts two and come back to you.

**Comment by Xwilarg** [comment] 2020-12-19 15:12
URL issue should now be fixed with version 1.2.2

**Comment by JayFlowGT** [comment] 2020-12-24 05:52
![image](https://user-images.githubusercontent.com/40595555/103064515-6c663700-45b4-11eb-9bbf-57abdc1b15e1.png)
currently having this issue

**Comment by Xwilarg** [comment] 2020-12-24 14:16
Did you try going in "Settings" and doing "Force Update"?
Also please make sure you are logged in NHentai

**Comment by JayFlowGT** [comment] 2020-12-25 04:26
did both. same thing in settings
![image](https://user-images.githubusercontent.com/40595555/103119008-c1b44e00-4671-11eb-84e5-0371e4a762ff.png)

**Comment by Xwilarg** [comment] 2020-12-25 04:55
Could you check the background console in chrome://extensions and tell me if you see any error?

**Comment by JayFlowGT** [comment] 2020-12-25 16:58
completely blank

**Comment by Xwilarg** [comment] 2021-01-12 19:36
Hi again, sorry for my lack of answer
I wasn't able to reproduce the issue on my computer, could you please tell me what is your OS, the browser you're using and its version?

**Comment by JayFlowGT** [comment] 2021-01-16 21:14
I am on latest Windows 10 and Google Chrome versions.

**Comment by Xwilarg** [comment] 2021-01-16 21:25
Can you please go in chrome://settings/help and confirm me your version?
If I still can't find the issue, I would need to send you a debug build if it's okay with you.

**Comment by JayFlowGT** [comment] 2021-01-17 21:33
I forgot to do the good old turn off and on again tactic. Just removed the extension and downloaded it again.
Seems to work for now, maybe because of some incompatibility between the versions. Not sure.
I will update you, if the problem comes back.

**Comment by Xwilarg** [comment] 2021-01-17 21:39
Well that was weird but at least, I'm glad it's working.

**Comment by Conando025** [comment] 2021-02-04 21:30
Hi, so I just wanted to let people know that I have a fork of the project that has a dark mode. But there is no toggle since CSS is utter garbage and I'm too lazy to figure it out.

**Comment by Xwilarg** [comment] 2021-02-04 21:51
> 
> 
> Hi, so I just wanted to let people know that I have a fork of the project that has a dark mode. But there is no toggle since CSS is utter garbage and I'm too lazy to figure it out.

Well if it's okay with you, please make a PR and I'll add an option to toggle on/off the dark mode in a few day

**Comment by Xwilarg** [comment] 2021-02-04 22:06
Also since this issue is starting to become a bit long, I'll close it.
If you need anything, feel free to open a new one or create a [discution](https://github.com/Xwilarg/NHentaiAnalytics/discussions)

**Closed as completed by Xwilarg** 2021-02-04 22:06 UTC
Labels: bug
